#!/usr/bin/env python
# -*- coding: utf-8 -*-

################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Author: Leon Jung, Gilbert

import rospy, roslaunch
import numpy as np
import subprocess
from std_msgs.msg import UInt8
import math
import os
import cv2
from enum import Enum
from std_msgs.msg import UInt8
from sensor_msgs.msg import Image, CompressedImage
from cv_bridge import CvBridge, CvBridgeError
from geometry_msgs.msg import Twist
from std_msgs.msg import String
import sys, select, os
import tty, termios
import time

WAFFLE_MAX_LIN_VEL = 0.26
WAFFLE_MAX_ANG_VEL = 1.82

LIN_VEL_STEP_SIZE = 0.01
ANG_VEL_STEP_SIZE = 0.1

msg = """
Control Your TurtleBot3!
---------------------------
Moving around:
        w
   a    s    d
        x

w/x : increase/decrease linear velocity (Burger : ~ 0.22, Waffle and Waffle Pi : ~ 0.26)
a/d : increase/decrease angular velocity (Burger : ~ 2.84, Waffle and Waffle Pi : ~ 1.82)

space key, s : force stop

CTRL-C to quit
"""

e = """
Communications Failed
"""

def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key

def vels(target_linear_vel, target_angular_vel):
    return "currently:\tlinear vel %s\t angular vel %s " % (target_linear_vel,target_angular_vel)

def makeSimpleProfile(output, input, slop):
    if input > output:
        output = min( input, output + slop )
    elif input < output:
        output = max( input, output - slop )
    else:
        output = input

    return output

def constrain(input, low, high):
    if input < low:
      input = low
    elif input > high:
      input = high
    else:
      input = input

    return input

def checkLinearLimitVelocity(vel):
    vel = constrain(vel, -WAFFLE_MAX_LIN_VEL, WAFFLE_MAX_LIN_VEL)
    return vel

def checkAngularLimitVelocity(vel):
    vel = constrain(vel, -WAFFLE_MAX_ANG_VEL, WAFFLE_MAX_ANG_VEL)
    return vel

"""
def mode_change():
    uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)    
    ros_package_path = os.path.dirname(os.path.realpath(__file__))
    ros_package_path = ros_package_path.replace('turtlebot3_autorace_detect/nodes', '')
      
    rospy.loginfo("herrererer!!!!!!!!!!!!!!!")
    #rospy.loginfo(self.child_zone)
    school_zone = roslaunch.scriptapi.ROSLaunch()
    school_zone = roslaunch.parent.ROSLaunchParent(uuid, [ros_package_path + "turtlebot3_autorace_detect/launch/turtlebot3_teleop_key.launch"])
    school_zone.start()
"""

#ob.Decider()

SELECTION = "None"
#NUMBER = 0

class DetectSign():
    def __init__(self):
        self.child_zone = 0
        self.uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)    
        self.ros_package_path = os.path.dirname(os.path.realpath(__file__))
        self.ros_package_path = self.ros_package_path.replace('turtlebot3_autorace_detect/nodes', '')
        
        self.fnPreproc()

        self.sub_image_type = "raw" # you can choose image type "compressed", "raw"
        self.pub_image_type = "compressed" # you can choose image type "compressed", "raw"

        
        if self.sub_image_type == "compressed":
            # subscribes compressed image
            self.sub_image_original = rospy.Subscriber('/detect/image_input/compressed', CompressedImage, self.cbFindTrafficSign, queue_size = 1)
        elif self.sub_image_type == "raw":
            # subscribes raw image
            self.sub_image_original = rospy.Subscriber('/detect/image_input', Image, self.cbFindTrafficSign, queue_size = 1)
        
        self.pub_traffic_sign = rospy.Publisher('/detect/traffic_sign', UInt8, queue_size=1)

        if self.pub_image_type == "compressed":
            # publishes traffic sign image in compressed type 
            self.pub_image_traffic_sign = rospy.Publisher('/detect/image_output/compressed', CompressedImage, queue_size = 1)
        elif self.pub_image_type == "raw":
            # publishes traffic sign image in raw type
            self.pub_image_traffic_sign = rospy.Publisher('/detect/image_output', Image, queue_size = 1)
    
        self.cvBridge = CvBridge()

        self.TrafficSign = Enum('TrafficSign', 'divide stop SPEED_30 slow child parking tunnel consturction fog animal snow')

        self.counter = 1

    def get_child_zone(self):
        return self.child_zone

    def fnPreproc(self):
        # Initiate SIFT detector
        self.sift = cv2.xfeatures2d.SIFT_create()

        dir_path = os.path.dirname(os.path.realpath(__file__))
        dir_path = dir_path.replace('turtlebot3_autorace_detect/nodes', 'turtlebot3_autorace_detect/')
        dir_path += 'file/detect_sign/'

        self.img2 = cv2.imread(dir_path + 'stop.png',0)         # trainImage1
        self.img3 = cv2.imread(dir_path + 'SPEED_30.png',0)      # trainImage2
        self.img4 = cv2.imread(dir_path + 'slow.png',0)       # trainImage3
        self.img5 = cv2.imread(dir_path + 'child.png',0)       # trainImage4
        self.img6 = cv2.imread(dir_path + 'tunnel.png',0)       # trainImage5

        """
        self.img6 = cv2.imread(dir_path + 'parking.png',0)       # trainImage5
        self.img7 = cv2.imread(dir_path + 'tunnel.png',0)       # trainImage6
        self.img8 = cv2.imread(dir_path + 'construction.png',0)       # trainImage7
        self.img9 = cv2.imread(dir_path + 'fog.png',0)       # trainImage8
        self.img10 = cv2.imread(dir_path + 'animal.png',0)       # trainImage9
        self.img11 = cv2.imread(dir_path + 'snow.png',0)       # trainImage10
        """

        self.kp2, self.des2 = self.sift.detectAndCompute(self.img2,None)
        self.kp3, self.des3 = self.sift.detectAndCompute(self.img3,None)
        self.kp4, self.des4 = self.sift.detectAndCompute(self.img4,None)
        self.kp5, self.des5 = self.sift.detectAndCompute(self.img5,None)
        self.kp6, self.des6 = self.sift.detectAndCompute(self.img6,None)
        
        """
        self.kp6, self.des6 = self.sift.detectAndCompute(self.img6,None)
        self.kp7, self.des7 = self.sift.detectAndCompute(self.img7,None)
        self.kp8, self.des8 = self.sift.detectAndCompute(self.img8,None)
        self.kp9, self.des9 = self.sift.detectAndCompute(self.img9,None)
        self.kp10, self.des10 = self.sift.detectAndCompute(self.img10,None)
        self.kp11, self.des11 = self.sift.detectAndCompute(self.img11,None)
        """
        FLANN_INDEX_KDTREE = 0
        index_params = dict(algorithm = FLANN_INDEX_KDTREE, trees = 5)
        search_params = dict(checks = 50)

        self.flann = cv2.FlannBasedMatcher(index_params, search_params)

    def fnCalcMSE(self, arr1, arr2):
            squared_diff = (arr1 - arr2) ** 2
            sum = np.sum(squared_diff)
            num_all = arr1.shape[0] * arr1.shape[1] #cv_image_input and 2 should have same shape
            err = sum / num_all
            return err

    def talker(self, detected):
        # pass the information
        pub = rospy.Publisher('chatter', String, queue_size=10)
        #rospy.init_node('talker', anonymous=True)
        rate = rospy.Rate(10) # 10hz
                    
        rospy.loginfo(detected)
        pub.publish(detected)

        #while not rospy.is_shutdown(): # without while it is executed just once.
        #which_sign = "please stop the car..."
        #rospy.loginfo(which_sign)
        #pub.publish(which_sign)
        #rate.sleep() # print every 10 seconds
    
    """
    def Repeat(self, sub_image_type):
        if self.sub_image_type == "compressed":
            # subscribes compressed image
            self.sub_image_original = rospy.Subscriber('/detect/image_input/compressed', CompressedImage, self.cbFindTrafficSign, queue_size = 1)
        elif self.sub_image_type == "raw":
            # subscribes raw image
            self.sub_image_original = rospy.Subscriber('/detect/image_input', Image, self.cbFindTrafficSign, queue_size = 1)
        print(self.child_zone)
    """    
    def cbFindTrafficSign(self, image_msg):    
        #ob = Decider()
        # drop the frame to 1/5 (6fps) because of the processing speed. This is up to your computer's operating power. 
        if self.counter % 3 != 0:
            self.counter += 1
            return
        else:
            self.counter = 1

        if self.sub_image_type == "compressed":
            #converting compressed image to opencv image
            np_arr = np.fromstring(image_msg.data, np.uint8)
            cv_image_input = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
        elif self.sub_image_type == "raw":
            cv_image_input = self.cvBridge.imgmsg_to_cv2(image_msg, "bgr8")

        MIN_MATCH_COUNT = 9
        MIN_MSE_DECISION = 50000

        # find the keypoints and descriptors with SIFT
        kp1, des1 = self.sift.detectAndCompute(cv_image_input,None)

        matches2 = self.flann.knnMatch(des1,self.des2,k=2)
        matches3 = self.flann.knnMatch(des1,self.des3,k=2)
        matches4 = self.flann.knnMatch(des1,self.des4,k=2)
        matches5 = self.flann.knnMatch(des1,self.des5,k=2)
        matches6 = self.flann.knnMatch(des1,self.des6,k=2)

        """
        matches6 = self.flann.knnMatch(des1,self.des6,k=2)
        matches7 = self.flann.knnMatch(des1,self.des7,k=2)
        matches8 = self.flann.knnMatch(des1,self.des8,k=2)
        matches9 = self.flann.knnMatch(des1,self.des9,k=2)
        matches10 = self.flann.knnMatch(des1,self.des10,k=2)
        matches11 = self.flann.knnMatch(des1,self.des11,k=2)
        """
        image_out_num = 1

        good2 = []
        for m,n in matches2:
            if m.distance < 0.7*n.distance:
                good2.append(m)

        if len(good2)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good2 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp2[m.trainIdx].pt for m in good2 ]).reshape(-1,1,2)

            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask2 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.stop.value

                self.pub_traffic_sign.publish(msg_sign)

                rospy.loginfo("TrafficSign 2")

                image_out_num = 2
                SELECTION = "stop"
                
                #rospy.loginfo(SELECTION)
                #which_sign = "stop"
                #pub.publish(which_sign)
                
        
        else:
            matchesMask2 = None

        good3 = []
        for m,n in matches3:
            if m.distance < 0.7*n.distance:
                good3.append(m)

        if len(good3)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good3 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp3[m.trainIdx].pt for m in good3 ]).reshape(-1,1,2)

            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask3 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.SPEED_30.value

                self.pub_traffic_sign.publish(msg_sign)

                rospy.loginfo("TrafficSign 3")

                image_out_num = 3
                SELECTION = "SPEED_30"

        else:
            matchesMask3 = None

        good4 = []
        for m,n in matches4:
            if m.distance < 0.7*n.distance:
                good4.append(m)
        if len(good4)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good4 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp4[m.trainIdx].pt for m in good4 ]).reshape(-1,1,2)

            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask4 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.slow.value

                self.pub_traffic_sign.publish(msg_sign)

                rospy.loginfo("TrafficSign 4")

                image_out_num = 4
                SELECTION = "slow"

        else:
            matchesMask4 = None

        good5 = []
        for m,n in matches5:
            if m.distance < 0.7*n.distance:
                good5.append(m)
        if len(good5)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good5 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp5[m.trainIdx].pt for m in good5 ]).reshape(-1,1,2)

            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask5 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.child.value

                self.pub_traffic_sign.publish(msg_sign)

                rospy.loginfo("TrafficSign 5")

                image_out_num = 5
                SELECTION = "child"                


        else:
            matchesMask5 = None

        
        good6 = []
        for m,n in matches6:
            if m.distance < 0.7*n.distance:
                good6.append(m)

        if len(good6)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good6 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp6[m.trainIdx].pt for m in good6 ]).reshape(-1,1,2)
 
            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask6 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.tunnel.value

                rospy.loginfo("TrafficSign 6")

                image_out_num = 6
                SELECTION = "tunnel"

        else:
            matchesMask6 = None

        """
        good6 = []
        for m,n in matches6:
            if m.distance < 0.7*n.distance:
                good6.append(m)

        if len(good6)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good6 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp6[m.trainIdx].pt for m in good6 ]).reshape(-1,1,2)
 
            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask6 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.parking.value

                #self.pub_traffic_sign.publish(msg_sign) 

                rospy.loginfo("TrafficSign 6")

                image_out_num = 6
                SELECTION = image_out_num

        else:
            matchesMask6 = None
    

        good7 = []
        for m,n in matches7:
            if m.distance < 0.7*n.distance:
                good7.append(m)

        if len(good7)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good7 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp7[m.trainIdx].pt for m in good7 ]).reshape(-1,1,2)

            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask7 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.tunnel.value
                
                #self.pub_traffic_sign.publish(msg_sign)

                rospy.loginfo("TrafficSign 7")

                image_out_num = 7
                SELECTION = image_out_num

        else:
            matchesMask7 = None


        good8 = []
        for m,n in matches8:
            if m.distance < 0.7*n.distance:
                good8.append(m)

        if len(good8)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good8 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp8[m.trainIdx].pt for m in good8 ]).reshape(-1,1,2)

            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask8 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.construction.value

                #self.pub_traffic_sign.publish(msg_sign)

                rospy.loginfo("TrafficSign 8")

                image_out_num = 8
                SELECTION = image_out_num
                
        else:
            matchesMask8 = None

        good9 = []
        for m,n in matches9:
            if m.distance < 0.7*n.distance:
                good9.append(m)

        if len(good9)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good9 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp9[m.trainIdx].pt for m in good9 ]).reshape(-1,1,2)

            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask9 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.fog.value
                #self.pub_traffic_sign.publish(msg_sign)

                rospy.loginfo("TrafficSign 9")

                image_out_num = 9
                SELECTION = image_out_num

        else:
            matchesMask9 = None

        good10 = []
        for m,n in matches10:
            if m.distance < 0.7*n.distance:
                good10.append(m)

        if len(good10)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good10 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp10[m.trainIdx].pt for m in good10 ]).reshape(-1,1,2)

            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask10 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.slow.value
                #self.pub_traffic_sign.publish(msg_sign)

                rospy.loginfo("TrafficSign 10")

                image_out_num = 10
                SELECTION = image_out_num

        else:
            matchesMask10 = None

        good11 = []
        for m,n in matches11:
            if m.distance < 0.7*n.distance:
                good11.append(m)

        if len(good11)>MIN_MATCH_COUNT:
            src_pts = np.float32([ kp1[m.queryIdx].pt for m in good11 ]).reshape(-1,1,2)
            dst_pts = np.float32([ self.kp11[m.trainIdx].pt for m in good11 ]).reshape(-1,1,2)

            M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)
            matchesMask11 = mask.ravel().tolist()

            mse = self.fnCalcMSE(src_pts, dst_pts)
            if mse < MIN_MSE_DECISION:
                msg_sign = UInt8()
                msg_sign.data = self.TrafficSign.snow.value

                #self.pub_traffic_sign.publish(msg_sign)

                rospy.loginfo("TrafficSign 11")

                image_out_num = 11
                SELECTION = image_out_num

        else:
            matchesMask11 = None

        """

        
        if image_out_num == 1:
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(cv_image_input, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(cv_image_input, "bgr8"))
        
        if image_out_num == 2:
            draw_params2 = dict(matchColor = (0,0,255), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask2, # draw only inliers
                            flags = 2)

            final2 = cv2.drawMatches(cv_image_input,kp1,self.img2,self.kp2,good2,None,**draw_params2)
            self.talker(SELECTION)
            #ob.talker(SELECTION)
            #pub.publish("stop")
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final2, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final2, "bgr8"))
            
        elif image_out_num == 3:
            draw_params3 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask3, # draw only inliers
                            flags = 2)

            final3 = cv2.drawMatches(cv_image_input,kp1,self.img3,self.kp3,good3,None,**draw_params3)
            self.talker(SELECTION)
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final3, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final3, "bgr8"))
            
        elif image_out_num == 4:
            draw_params4 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask4, # draw only inliers
                            flags = 2)

            final4 = cv2.drawMatches(cv_image_input,kp1,self.img4,self.kp4,good4,None,**draw_params4)
            self.talker(SELECTION)
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final4, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final4, "bgr8"))
            
        elif image_out_num == 5:
            draw_params5 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask5, # draw only inliers
                            flags = 2)

            final5 = cv2.drawMatches(cv_image_input,kp1,self.img5,self.kp5,good5,None,**draw_params5)
            self.talker(SELECTION)
            #self.mode_change(image_out_num)

            #self.child_zone = 5
            #rospy.loginfo("CAME IN!!!!!")
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final5, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final5, "bgr8"))
                
        elif image_out_num == 6:
            draw_params6 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask6, # draw only inliers
                            flags = 2)

            final6 = cv2.drawMatches(cv_image_input,kp1,self.img6,self.kp6,good6,None,**draw_params6)
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final6, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final6, "bgr8"))
        
    """
        elif image_out_num == 6:
            draw_params6 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask6, # draw only inliers
                            flags = 2)

            final6 = cv2.drawMatches(cv_image_input,kp1,self.img6,self.kp6,good6,None,**draw_params6)
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final6, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final6, "bgr8"))
            
        elif image_out_num == 7:
            draw_params7 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask7, # draw only inliers
                            flags = 2)

            final7 = cv2.drawMatches(cv_image_input,kp1,self.img7,self.kp7,good7,None,**draw_params7)
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final7, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final7, "bgr8"))
            
        elif image_out_num == 8:
            draw_params8 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask8, # draw only inliers
                            flags = 2)

            final8 = cv2.drawMatches(cv_image_input,kp1,self.img8,self.kp8,good8,None,**draw_params8)
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final8, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final8, "bgr8"))
            
        elif image_out_num == 9:
            draw_params9 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask9, # draw only inliers
                            flags = 2)

            final9 = cv2.drawMatches(cv_image_input,kp1,self.img9,self.kp9,good9,None,**draw_params9)
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final9, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final9, "bgr8"))
            
        elif image_out_num == 10:
            draw_params10 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask10, # draw only inliers
                            flags = 2)

            final10 = cv2.drawMatches(cv_image_input,kp1,self.img10,self.kp10,good10,None,**draw_params10)
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final10, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final10, "bgr8"))
            
        elif image_out_num == 11:
            draw_params11 = dict(matchColor = (255,0,0), # draw matches in green color
                            singlePointColor = None,
                            matchesMask = matchesMask11, # draw only inliers
                            flags = 2)

            final11 = cv2.drawMatches(cv_image_input,kp1,self.img11,self.kp11,good11,None,**draw_params11)
            
            if self.pub_image_type == "compressed":
                # publishes traffic sign image in compressed type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_compressed_imgmsg(final11, "jpg"))

            elif self.pub_image_type == "raw":
                # publishes traffic sign image in raw type
                self.pub_image_traffic_sign.publish(self.cvBridge.cv2_to_imgmsg(final11, "bgr8"))
            
    """
    """
    def starter(self):
        pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)

        status = 0
        target_linear_vel   = 0.0
        target_angular_vel  = 0.0
        control_linear_vel  = 0.0
        control_angular_vel = 0.0

        while(1):
            rospy.loginfo("i am here")
            target_linear_vel = 0.01
            print vels(target_linear_vel,target_angular_vel)

        twist = Twist()

        control_linear_vel = makeSimpleProfile(control_linear_vel, target_linear_vel, (LIN_VEL_STEP_SIZE/2.0))
        twist.linear.x = control_linear_vel; twist.linear.y = 0.0; twist.linear.z = 0.0

        control_angular_vel = makeSimpleProfile(control_angular_vel, target_angular_vel, (ANG_VEL_STEP_SIZE/2.0))
        twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = control_angular_vel
                    
        pub.publish(twist)
    """

    """
    def mode_change(self, num):
        uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)    
        ros_package_path = os.path.dirname(os.path.realpath(__file__))
        ros_package_path = ros_package_path.replace('turtlebot3_autorace_detect/nodes', '')
        
        while(1):
            rospy.loginfo(self.child_zone)
            if(num == 5):
                rospy.loginfo("herrererer!!!!!!!!!!!!!!!")

                #rospy.loginfo(self.child_zone)
                school_zone = roslaunch.scriptapi.ROSLaunch()
                school_zone = roslaunch.parent.ROSLaunchParent(uuid, [ros_package_path + "turtlebot3_autorace_detect/launch/turtlebot3_teleop_key.launch"])
                school_zone.start()
                
            else:
                rospy.loginfo("NOT!!!!")
            rospy.sleep(1)
    """

    def main(self):
        rospy.spin()  

if __name__ == '__main__':
    rospy.init_node('detect_sign')
    node = DetectSign()
    #node.mode_change(node.get_child_zone())
    node.main()

"""
    pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)

    status = 0
    target_linear_vel   = 0.0
    target_angul)ar_vel  = 0.0
    control_linear_vel  = 0.0
    control_angular_vel = 0.0

    while(1):
        target_linear_vel = 0.01
        print vels(target_linear_vel,target_angular_vel)

    twist = Twist()

    control_linear_vel = makeSimpleProfile(control_linear_vel, target_linear_vel, (LIN_VEL_STEP_SIZE/2.0))
    twist.linear.x = control_linear_vel; twist.linear.y = 0.0; twist.linear.z = 0.0

    control_angular_vel = makeSimpleProfile(control_angular_vel, target_angular_vel, (ANG_VEL_STEP_SIZE/2.0))
    twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = control_angular_vel
                    
    pub.publish(twist)
"""    
"""
    try:
        print msg
        while(1):
            target_linear_vel = 0.01
            print vels(target_linear_vel,target_angular_vel)

            key = getKey()
            if key == 'w' :
                target_linear_vel = checkLinearLimitVelocity(target_linear_vel + LIN_VEL_STEP_SIZE)
                status = status + 1
                print(vels(target_linear_vel,target_angular_vel))
            elif key == 'x' :
                target_linear_vel = checkLinearLimitVelocity(target_linear_vel - LIN_VEL_STEP_SIZE)
                status = status + 1
                print(vels(target_linear_vel,target_angular_vel))
            elif key == 'a' :
                target_angular_vel = checkAngularLimitVelocity(target_angular_vel + ANG_VEL_STEP_SIZE)
                status = status + 1
                print(vels(target_linear_vel,target_angular_vel))
            elif key == 'd' :
                target_angular_vel = checkAngularLimitVelocity(target_angular_vel - ANG_VEL_STEP_SIZE)
                status = status + 1
                print(vels(target_linear_vel,target_angular_vel))
            elif key == ' ' or key == 's' :
                target_linear_vel   = 0.0
                control_linear_vel  = 0.0
                target_angular_vel  = 0.0
                control_angular_vel = 0.0
                print(vels(target_linear_vel, target_angular_vel))
            else:
                if (key == '\x03'):
                    break

            twist = Twist()

            control_linear_vel = makeSimpleProfile(control_linear_vel, target_linear_vel, (LIN_VEL_STEP_SIZE/2.0))
            twist.linear.x = control_linear_vel; twist.linear.y = 0.0; twist.linear.z = 0.0

            control_angular_vel = makeSimpleProfile(control_angular_vel, target_angular_vel, (ANG_VEL_STEP_SIZE/2.0))
            twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = control_angular_vel

            pub.publish(twist)

    except:
        print e

"""