#!/usr/bin/env python

import rospy
import roslaunch
"""
from geometry_msgs.msg import Twist
import sys, select, os
import tty, termios
from std_msgs.msg import String
"""
rospy.init_node('tester', anonymous=True)

uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)
roslaunch.configure_logging(uuid)
launch = roslaunch.parent.ROSLaunchParent(uuid,["/home/woosoo/catkin_ws/src/turtlebot3_autorace/turtlebot3_autorace_detect/launch/turtlebot3_teleop_key.launch"])

launch.start()

"""
class Mode():
  
    def __init__(self):
       
        self.uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)    
        self.ros_package_path = os.path.dirname(os.path.realpath(__file__))
        self.ros_package_path = self.ros_package_path.replace('turtlebot3_autorace_detect/nodes', '')
   

    
   
    
    def mode_controll(self):
        dir_path = os.path.dirname(os.path.realpath(__file__))
        
        dir_path = dir_path.replace('turtlebot3_autorace_detect/nodes', 'turtlebot3_autorace_detect/launch')
        self.launch_detect_stop = roslaunch.scriptapi.ROSLaunch()
        self.launch_detect_stop = roslaunch.parent.ROSLaunchParent(self.uuid, [self.ros_package_path + "turtlebot3_autorace_detect/launch/turtlebot3_teleop_key.launch"])
        self.launch_detect_stop.start()
    
    def main(self):
        rospy.spin()

if __name__ == '__main__':
    rospy.init_node('mode_change')
    node = Mode()
    node.mode_controll()
"""